### ISSUE TITLE
Scenario "Export posts using --max_num_posts" fails on Mac OS X

### ISSUE THREAD

**Issue by schlessera** [wp-cli/export-command#23]
The Behat test scenario "Export posts using --max_num_posts" fails on Mac OS X:

<img width="1024" alt="image 2017-10-25 at 10 07 26 am" src="https://user-images.githubusercontent.com/83631/31987511-53e043ce-b96c-11e7-8044-a9b218d8f5ec.png">

**Comment by miya0001** [comment]
There are similar problems on wp-cli/wp-cli like following.

```
    When I run `TERM=vt100 COLUMNS=80 wp help test-wordwrap | wc -L`                               # features/steps/when.php:29
      $ TERM=vt100 COLUMNS=80 wp help test-wordwrap | wc -L
      
      wc: illegal option -- L
      usage: wc [-clmw] [file ...]
      cwd: /var/folders/r8/93smf9ld3lgdsn7ly3s5hj940000gr/T/wp-cli-test-run-help.feature.833-59f04f939bb347.62200143/
      run time: 0.27075505256653
      exit status: 1
```

Do you have any idea to fix those problem?

**Comment by schlessera** [comment]
@miya0001 Yes, see https://github.com/wp-cli/wp-cli/issues/4466
