### ISSUE TITLE
can't set with_attachments to FALSE

### ISSUE THREAD

**Issue by drzraf** [wp-cli/export-command#40]
Followup of #16
There was introduced `--with_attachments`. During the course of the PR, validation/casting disappeared and argument was handled that way:
```
+		$this->export_args['with_attachments'] = WP_CLI\Utils\get_flag_value(
+			$assoc_args,
+			'with_attachments',
+			$defaults['with_attachments']
+		);
```

But [on the other side](https://github.com/wp-cli/export-command/blob/master/src/WP_Export_Query.php#L199), the code test for **boolean** value.
== we can't force `--with_attachment` to FALSE whatever the value passed would be (`=0, =no, =false, ...`)

Ref to [get_flag_value](https://github.com/wp-cli/wp-cli/blob/master/php/utils.php#L742)

**Comment by schlessera** [comment]
@drzraf The way to negate a flag is to add `no-` in front of it:
```
--on-with_attachments
```

This is part of the default Synopsis handling of WP-CLI.

**Comment by schlessera** [comment]
@drzraf Can you confirm this is what you were intending to do with this PR?

**Comment by drzraf** [comment]
More or less. My main goal was to get it work in combination with `--post_type`.
I didn't remember about the "no-with" syntax (can't be more counter-intuitive), and intended to add support for argument value. From one side, `--no-with_attachments` didn't work previously in combination of `--post_type`.

**Comment by schlessera** [comment]
I conclude that your current use case is solved and that I can close the current issue and corresponding pull-request.

**Comment by drzraf** [comment]
I'd need to test this again, but this hunk: https://github.com/wp-cli/export-command/pull/41/files#diff-62b6f83678ae9c3aaa96e7b97dce0433R163
make possible to specify **both** `post_type` and NO attachments.
