### ISSUE TITLE
wp export --post_type=attachment does not export postmeta

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/export-command#53]
Could it be that postmeta (e.g. `_wp_attached_file` and `_wp_attachment_metadata`) does not get exported?

**Comment by swissspidy** [comment]
Yes, these two fields are skipped, see https://github.com/wp-cli/export-command/blob/776d33ad6b2ac93c00fded27402ca8e188e7bff0/src/WP_Export_Query.php#L362-L375

**Comment by szepeviktor** [comment]
Ohh! Thank you.

As it is hardcoded - I think - there is no solution for that.

**Comment by paulgibbs** [comment]
How would you prefer this to be fixed?

Would you prefer the array of the keys-to-be-skipped to be filterable?
And/or do you want the default behaviour to be kept as it is currently (e.g. do not export `'_wp_attachment_metadata', '_wp_attached_file' `)?

**Comment by szepeviktor** [comment]
I1d like both of them to be consistently exported.

**Comment by szepeviktor** [comment]
Thank you.
