### ISSUE TITLE
--category=<name> filter apparently not working

### ISSUE THREAD

**Issue by DrLightman** [wp-cli/export-command#64]
## Bug Report

**Describe the current, buggy behavior**

I launch a command like this:

`wp export --max_file_size=-1 --with_attachments --category=Rome --start_date=2020-03-01`

I tried with or without double quotes surrounding the category name. Uppercase, lowercase or with category id.

But all posts despite the specificed "Rome" category are included in the resulting xml.

I tried in minimal WP 5.3.2 installations too without any plugins installed, same outcome.

**Describe what you would expect as the correct outcome**

Only posts of category Rome (and eventually subcategories?) to be included in the xml export.

**Let us know what environment you are running this on**

```
OS:     Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php
PHP version:    7.4.2
php.ini used:   /etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html/
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
```

Thanks

**Comment by mzeis** [comment]
I experience the same issue with this version:

~~~
OS:  Linux 5.3.18-050318-generic #201912181133 SMP Wed Dec 18 16:36:09 UTC 2019 x86_64
Shell:  /usr/bin/zsh
PHP binary:     /usr/bin/php7.2
PHP version:    7.2.30-1+ubuntu18.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.2/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/
WP-CLI packages dir:    
WP-CLI global config:   
WP-CLI project config:  
WP-CLI version: 2.4.0
~~~

**Comment by wissensschatz** [comment]
Confirmed same issue with release 2.0.4 for this command on top of WP-CLI  2.4.0

**Comment by schlessera** [comment]
This seems to actually be user error. To use the filter, you'll need to use `--post_category=<category>`, not `--category=<category>`.

**Comment by DrLightman** [comment]
@schlessera 

No user's fault here, the documentation says to use `category` not `post_category`.

https://developer.wordpress.org/cli/commands/export/

```
[--category=<name>]
Export only posts in this category.
```

**Comment by schlessera** [comment]
@DrLightman Yes, indeed, I realized this as well going through the tests again. However, I still can't replicate this...
