### ISSUE TITLE
Export is missing `cat_name`, `tag_name` & `term_name`

### ISSUE THREAD

**Issue by dimaeromin97** [wp-cli/export-command#85]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
I really like to automate my content export with "wp export", it's very easy and fast, but.
Аfter upgrading to WP 5.8 in the file content.xml missing data "cat_name, tag_name, term_name" because of this when importing errors.

https://i.imgur.com/9XavHps.png
https://i.imgur.com/LPiWbtc.png

thanks.

**Let us know what environment you are running this on**

```
OS: Linux 3.12.18-clouder0 #6 SMP PREEMPT Mon Apr 12 16:04:39 EEST 2021 x86_64
Shell: /bin/bash
PHP binary: /usr/local/php74/bin/php-cli
PHP version: 7.4.21
php.ini used: /usr/local/php74/lib/php.ini
MySQL binary: /bin/mysql
MySQL version: mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for Linux (x86_64) using readline 5.1
SQL modes: 
WP-CLI root dir: phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir: phar://wp-cli.phar/vendor
WP_CLI phar path: /home/customer/www/yaffotheme.com/public_html
WP-CLI packages dir: 
WP-CLI global config: 
WP-CLI project config: 
WP-CLI version: 2.5.0
```

**Comment by dimaeromin97** [comment]
I found a temporary solution ```wp eval "require_once ABSPATH . 'wp-admin/includes/export.php'; export_wp( [ 'content' => 'all' ] );"```

**Comment by schlessera** [comment]
It looks like this is unrelated to WP 5.8, but is rather a regression that was introduced via #84 .
