### ISSUE TITLE
Export WXR files to STDOUT

### ISSUE THREAD

**Issue by drzraf** [wp-cli/export-command#9]
Currently it's not easy to dump the XML to stdout.
The only way is to trick the program using `--dir=/dev --filename_format=stdout`
But even then, it won't work if command is piped (blocking/non-blocking IO ?)
Would it be possible to have a `-o|--output` flag which, if value is "-", is considered as stdout.

Then we could do:
`wp --quiet  --post_type=foo --post_status=publish -o - | xsltproc -stringparam hostreplace https://preproduction make-preprod.xsl - | xz -9 | gpg -c > dump.xml.xz.gpg`
See https://github.com/humanmade/WordPress-Importer/issues/136 about the hope for adding ` | ssh preprod "wp wxr-importer import -"` to the chain

**Comment by danielbachhuber** [comment]
> Would it be possible to have a `-o|--output` flag which, if value is "-", is considered as stdout.

This seems reasonable if it's technically feasible.

**Comment by danielbachhuber** [comment]
Related: `wp search-replace [--export[=<file>]]`, which writes to `STDOUT` when `--export` is provided as the argument.
